{% set name = "pgsqlite" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgsqlite-{{ version }}.tar.gz
  sha256: 3e778c5266aec65e36fc67cf3dca1d84982941f58e9510a39e9d0188e9929f82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sqlite-utils >=3.28
    - psycopg >=3.1
    - psycopg-c >=3.1
    - structlog >=22.1.0
    - sqlglot >=6.1.0

test:
  requires:
    - python {{ python_min }}
  source_files:
    - pgsqlite
  imports:
    - pgsqlite
  commands:
    - python ./pgsqlite/pgsqlite.py -h

about:
  home: https://github.com/bitdotioinc/pgsqlite
  summary: Loader to import sqlite3 databases into Postgres
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
